# Generated by Django 5.1.1 on 2024-09-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_done", "-created_at")},
        ),
    ]
